### ISSUE TITLE
Can't compile with ROS indigo

### ISSUE THREAD

**Issue by daniel86** [robcog-iai/unreal_ros_pkgs#3]
yes I know indigo is old.

here is the output: https://pastebin.ca/4010779

**Comment by andreihaidu** [comment]
just remove the example code `src` folder (does are only for testing there, they will eventually be removed, or moved to another package)

**Comment by daniel86** [comment]
Well I wouldn't close the issue as long as compile error still happens.
Then anyone running into this issue will see the ticket here
when consulting github.

however, compilation runs through without the source directory.
